// Package server defines the server for dime
package server

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strconv"

	"github.com/gorilla/mux"
	_ "github.com/johnmarkli/dime/docs" // docs generated by Swag CLI
	"github.com/johnmarkli/dime/pkg/store"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

const (
	defaultPort    = 8080
	defaultDataDir = "data"
)

// Server manages the lifecycle of the dime server
type Server struct {
	server *http.Server
}

// New creates a new Server instance
//
// Environment:
//
//	DIME_PORT
//	    int - port for server to listen on
//	DIME_DATA_DIR
//	    string - directory to save data to the file system
func New() (*Server, error) {
	router := mux.NewRouter()
	router.Use(loggingMiddleware)
	router = router.StrictSlash(true)
	port := getPort()

	// /health
	hh := HealthHandler{}
	router.HandleFunc("/health", hh.Check).Methods("GET")

	// /dicoms API
	st, err := store.NewFileStore(getDataDir())
	if err != nil {
		return nil, fmt.Errorf("failed to create store: %w", err)
	}
	dh := NewDICOMHandler(st)
	dicomsRouter := router.PathPrefix("/dicoms").Subrouter()
	dicomsRouter.HandleFunc("", dh.Upload).Methods("POST")
	dicomsRouter.HandleFunc("", dh.List).Methods("GET")
	dicomsRouter.HandleFunc("/{id}", dh.Read).Methods("GET")
	dicomsRouter.HandleFunc("/{id}/attributes", dh.Attributes).Methods("GET")
	dicomsRouter.HandleFunc("/{id}/image", dh.Image).Methods("GET")

	// /swagger docs
	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL(fmt.Sprintf("http://localhost:%d/swagger/doc.json", port)),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)

	s := &Server{
		server: &http.Server{
			Addr:    fmt.Sprintf(":%d", port),
			Handler: router,
		},
	}
	return s, nil
}

// Run the dime server
func (s *Server) Run() {
	slog.Info("Starting dime server", slog.String("on", s.server.Addr))
	go func() { _ = s.server.ListenAndServe() }()
}

// Shutdown the dime server
func (s *Server) Shutdown() {
	slog.Info("Shutting down dime server")
	_ = s.server.Shutdown(context.Background())
}

// Server returns the http server
func (s *Server) Server() *http.Server {
	return s.server
}

func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		slog.Info("Request received",
			slog.String("method", r.Method),
			slog.String("request", r.RequestURI))
		next.ServeHTTP(w, r)
	})
}

func getPort() int {
	port := defaultPort
	if val, ok := os.LookupEnv("DIME_PORT"); ok {
		if p, err := strconv.Atoi(val); err == nil {
			port = p
		}
	}
	return port
}

func getDataDir() string {
	dir := defaultDataDir
	if val, ok := os.LookupEnv("DIME_DATA_DIR"); ok {
		dir = val
	}
	return dir
}
